---
# tasks file for ansible-role-chrome

#- include: apt-installation.yml
#  when: ansible_pkg_mgr == 'apt'

# apt tasks file for ansible-role-chrome
# via http://linuxg.net/how-to-install-google-chrome-42-stable-on-the-most-popular-linux-systems-via-the-official-google-repository/

- name: install apt signing key
  apt_key: >
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state='{{ chrome_apt_key_state }}'

- name: 'ensure for chrome_stale repository state'
  apt_repository:
    mode: 0644
    repo: '{{ chrome_stale_apt_source_entry }}'
    state: '{{ chrome_stale_state }}'
    filename: '{{ chrome_sources_list_d_entry }}' # .list is appended by the module
    update_cache: yes
  when: chrome_stale_remove == True

- name: 'ensure for google-chrome debian repository'
  apt_repository:
    mode: 0644
    repo: '{{ chrome_stale_apt_source_entry }}'
    state: '{{ chrome_state }}'
    filename: '{{ chrome_sources_list_d_entry }}' # .list is appended by the module
    update_cache: yes
  register: google_repo

- name: "apt | update cache"
  apt: update_cache=yes
  when: google_repo.changed

- name: "Install (or remove) chrome apt package(s)"
  apt: >
    name='{{ item }}'
    state='{{ fsl_state }}'
  with_flattened:
    - '{{ chrome_apt_packages }}'
        tags: [ 'packages', 'utilities' ]
